### PR TITLE
close #23 ir remoter screen design

### LINKED ISSUE #23: IR Remoter Screen
Screen Shot 2021-05-16 at 8 45 02 AM

### PR DESCRIPTION
**Pull request by darot-chen**

### CODE REVIEW

**Comment by darot-chen** [comment]
Screen Shot 2021-05-22 at 9 00 03 PM

**Comment by darot-chen** [comment]
Screen Shot 2021-05-22 at 9 40 42 PM

**Comment by darot-chen** [comment]
@theacheng  FYI: The image above the buttons, I use (.png) because (.svg ) not support even I use the packages.

**Comment by theachoem** [comment]
We may update it later and use custom paint instead, but this already great!

**Pull request merged**
