### PR TITLE
28 sender screen

### PR DESCRIPTION
**Pull request by nonsinat**
image

### CODE REVIEW

**Comment by theachoem** [comment]
@nonsinat, make sure to use color from the design, make font size the same

**Comment by theachoem** [comment]
@nonsinat  there is also 2 commit, please remove one

Please let me know if there any problems!

**Comment by nonsinat** [comment]
i use random color ,

**Comment by theachoem** [comment]
@nonsinat done yet? I see it still in progress

**Comment by nonsinat** [comment]
ohh maybe i'm forgot move to done, but   i'm done about 1 week ago ,

**Comment by theachoem** [comment]
@nonsinat again, you should fix conflict

**Pull request merged**
